Selenium Task 40
alexcrtCS/UnitTesting pull request #4
Opened 2022-12-29 14:03 UTC by alexcrtCS

- Solved all exercises from list for Task 40
- Each solution in separate class

2023-01-04 22:24 UTC, irynaalex commented on src/test/java/ParameterizedLoginTest.java
> +        driver.findElement(PASS_FIELD).sendKeys(PASSWORD);
In the task we have: "with at least 2 different credentials", so it should be pair  (userName, password)

2023-01-04 22:24 UTC, irynaalex commented on src/test/java/ParameterizedLoginTest.java
> +        Thread.sleep(6000); // at least 5s are required to pass, else Selenium is flagged as suspicious activity
What type of waiter is it (add your answer as comment near sleep)?

2023-01-05 14:13 UTC, LikBez123 requested changes

2023-01-05 14:13 UTC, LikBez123 commented on src/test/java/EmployeeTest.java
> +    private final By TABLE_ROWS = By.xpath("//tr");
your locator also captures the header of the table, which is not needed

2023-01-05 14:13 UTC, LikBez123 commented on src/test/java/EmployeeTest.java
> +        } while (!driver.findElement(NEXT_BTN).getAttribute("class").endsWith("disabled"));
the approach is correct, but you will not collect data for the last pagination result page. By clicking the last time, you will immediately get button disabled without collecting data from the last page. Try this:
```
 boolean enabled = true;
        while (enabled) {
            WebElement nextBtn = driver.findElement(NEXT_BTN);
            List<WebElement> rowList = driver.findElements(TABLE_ROWS);
            for (WebElement row : rowList) {
                int actualAge = Integer.parseInt(row.findElement(AGE_CELLS).getText());
                int actualSalary = Integer.parseInt(row.findElement(SALARY_CELLS).getAttribute("data-order"));
                if (actualAge > minAge && actualSalary <= maxSalary) {
                    String name = row.findElement(NAME_CELLS).getText();
                    String position = row.findElement(POSITION_CELLS).getText();
                    String office = row.findElement(OFFICE_CELLS).getText();
                    Employee employee = new Employee(name, position, office);
                    employeeList.add(employee);
                }
            }
            if (!nextBtn.getAttribute("class").contains("disabled")) {
                nextBtn.click();
            } else {
                enabled = false;
            }
        }
```

2023-01-05 14:13 UTC, LikBez123 commented on src/test/java/UserTest.java
> +    void UserImageTest() {
the name of the methods begins with lowercase. Check all the tests

2023-01-05 15:02 UTC, LikBez123 approved these changes

2023-01-05 16:35 UTC, merged