Selenium Task 60 POM
alexcrtCS/UnitTesting pull request #5
Opened 2023-01-06 09:34 UTC by alexcrtCS

- Created Test Class with login and logout testing
- Implemented POM design pattern

2023-01-11 15:55 UTC, LikBez123 requested changes

2023-01-11 15:55 UTC, LikBez123 commented on src/main/java/pageclasses/WebDriverSingleton.java
> +    private final WebDriver driver;
it is better to use ThreadLocal to ensure thread safety
https://medium.com/10-minutes-qa-story/run-selenium-tests-in-parallel-with-singletone-driver-21ed058c6fad

2023-01-12 11:10 UTC, LikBez123 approved these changes

2023-01-12 15:10 UTC, irynaalex approved these changes

2023-01-12 15:27 UTC, merged